several fixes for FreeBSD

diff --git a/setupcon b/setupcon
--- a/setupcon
+++ b/setupcon
@@ -84,7 +84,15 @@ run () {
     case "$ttyarg" in
         plain)
             if [ "$do_verbose" ]; then
-                $cmd "$@" $verbose
+		case "$verbose" in
+		    ECHO)
+			report Executing $cmd "$@".
+			$cmd "$@"
+			;;
+		    *)
+			$cmd "$@" $verbose
+			;;
+		esac
             else
                 $cmd "$@" >/dev/null 2>&1
             fi
@@ -92,7 +100,7 @@ run () {
         in)
             for tty in $ACTIVE_CONSOLES; do
                 if [ -r $tty ]; then
-                    report Executing $cmd for $tty.
+                    report Executing for $tty.
                     run plain "$verbose" "$cmd" "$@" <$tty
                 else
                     report No read access from $tty. Can not execute $cmd.
@@ -122,8 +130,9 @@ findfile () {
             fi
             ;;
     esac
-    x=`ls "$installdir"/$1/$2 /usr/local/$1/$2 /usr/$1/$2
-          /etc/console-setup/$2 "$installdir"/etc/console-setup/$2` 2>/dev/null
+    x=`(ls "$installdir"/$1/$2 /usr/local/$1/$2
+	   /usr/$1/$2 /etc/console-setup/$2
+	   "$installdir"/etc/console-setup/$2) 2>/dev/null`
     x=`echo $x`
     [ "${x%% *}" ] || report Unable to find "$2".
     echo "${x%% *}"
@@ -262,7 +271,6 @@ else
 fi
 . "$CONFIG"
 
-
 ###########################################################################
 ### INITIALIZATION AND DEFAULT VALUES
 ###########################################################################
@@ -282,16 +290,18 @@ if which uname >/dev/null; then
 fi
 
 # do_save
-if [ -n "$do_save" -a ! -d /usr/share ]; then
-    echo It seems /usr is not mounted.  Will not save files in /etc. >&2
-    do_save=''
-elif [ ! -w /etc/console-setup/ ]; then
-    echo /etc/console-setup is not writable.  No files will be saved there. >&2
-    do_save=''
+if [ -n "$do_save" ]; then
+    if [ ! -d /usr/share ]; then
+        echo It seems /usr is not mounted.  Will not save files in /etc. >&2
+        do_save=''
+    elif [ ! -w /etc/console-setup/ ]; then
+        echo /etc/console-setup is not writable.  No files will be saved there. >&2
+        do_save=''
+    fi
 fi
 
 # ACTIVE_CONSOLES
-# When ACTIVE_CONSOLES=guess the following will make ACTIVE_CONSOLES=''
+# When ACTIVE_CONSOLES=guess the following will result in ACTIVE_CONSOLES=''
 ACTIVE_CONSOLES=$(
     for tty in $ACTIVE_CONSOLES; do
         if [ -e $tty ]; then
@@ -302,24 +312,30 @@ ACTIVE_CONSOLES=$(
 if [ -z "$ACTIVE_CONSOLES" ]; then
     # Some crude guess
     #  Conf. files:
+    #    BSD:        /etc/ttys
     #    Sys V init: /etc/inittab
-    #    Upstart: /etc/init/*
+    #    Upstart:    /etc/init/*
     #  Devices:
-    #    Linux: /dev/tty[1-9][0-9]*
+    #    Linux:   /dev/tty[1-9][0-9]*
     #    FreeBSD: /dev/ttyv[0-9a-f]
     for tty in \
-        $(cat /etc/inittab /etc/init/* 2>/dev/null \
-        | egrep '[[:blank:]]tty([1-9][0-9]*|v[0-f])([[:blank:]]|$)' \
+        $(cat /etc/inittab /etc/init/* /etc/ttys 2>/dev/null \
+	| grep getty \
+        | egrep '([[:blank:]]|^)tty([1-9][0-9]*|v[0-9a-f])([[:blank:]]|$)' \
         | sed -e '/^ *#/d' \
               -e 's/.*[[:blank:]]\(tty[1-9][0-9]*\).*/\1/' \
-              -e 's/.*[[:blank:]]\(ttyv[0-9]\).*/\1/')
+              -e 's/.*[[:blank:]]\(ttyv[0-9a-f]\).*/\1/')
     do
         if [ -e /dev/$tty ]; then
             ACTIVE_CONSOLES="$ACTIVE_CONSOLES /dev/$tty"
         fi
     done
 fi
-report Configuring $ACTIVE_CONSOLES
+if [ -z "$ACTIVE_CONSOLES" ]; then
+    echo Can not find the active virtual consoles >&2
+else
+    report Configuring $ACTIVE_CONSOLES
+fi
 
 # CHARMAP
 CHARMAP=${CHARMAP:-UTF-8}
@@ -449,8 +465,12 @@ case "$kernel" in
         mapdir=share/syscons/scrnmaps
         stdmap=${CHARMAP}_${CODESET}.scm
         fontdir=share/syscons/fonts
-        stdfont=$CODESET-$FONTFACE$FONTSIZE.fnt
-        stdfontfallback=$CODESET-*[A-Za-z]$FONTSIZE.fnt
+        stdfont16=$CODESET-${FONTFACE}16.fnt
+        stdfont14=$CODESET-${FONTFACE}14.fnt
+        stdfont8=$CODESET-${FONTFACE}8.fnt
+        stdfontfallback16=$CODESET-*[A-Za-z]16.fnt
+        stdfontfallback14=$CODESET-*[A-Za-z]14.fnt
+        stdfontfallback8=$CODESET-*[A-Za-z]8.fnt
         ;;
 esac
 
@@ -459,10 +479,7 @@ CONSOLE_MAP=${CONSOLE_MAP:-$ACM}
 [ -z "$CONSOLE_MAP" ] || CONSOLE_MAP=`findfile $mapdir "$CONSOLE_MAP"`
 [ -n "$CONSOLE_MAP" -o "$CHARMAP" = UTF-8 ] || CONSOLE_MAP=`findfile $mapdir $stdmap`
 
-# FONTFILES, VIDEOMODE
-if [ "$VIDEOMODE" = guess]; then
-    VIDEOMODE=''
-fi
+# FONTFILES
 FONTFILES=''
 if [ "$FONT" ]; then
     for f in $FONT; do
@@ -471,48 +488,39 @@ if [ "$FONT" ]; then
 fi
 FONTFILES=`echo $FONTFILES` # remove extra spaces
 if [ -n "$FONTFACE" -a -z "$FONTFILES" ]; then
-    # the following will fail if FONTFACE=guess ($stdfont will match nothing)
-    FONTFILES=`findfile $fontdir $stdfont`
-    [ "$FONTFILES" ] || FONTFILES=`findfile $fontdir $stdfontfallback`
-    case "$FONTFILES" in
-        *[0-9]x[1-9]*.psf.gz|*[0-9]x[1-9]*.fnt)
-            if [ "$kernel" = freebsd ]; then
-                echo "\
-Only fonts with 8 pixel width matrix are supported on the FreeBSD console.
-Please reconfigure the font size." >&2
-                FONTFILES=''
-            elif which consolechars >/dev/null; then
-		echo "\
+    case "$kernel" in
+        linux)
+            # the following will fail if FONTFACE=guess ($stdfont will
+            # match nothing)
+            FONTFILES=`findfile $fontdir $stdfont`
+            [ "$FONTFILES" ] || FONTFILES=`findfile $fontdir $stdfontfallback`
+            case "$FONTFILES" in
+                *[0-9]x[1-9]*.psf.gz)
+                    if which consolechars >/dev/null; then
+		        echo "\
 The consolechars utility from the \"console-tools\" package can load only fonts
 with 8 pixel width matrix.  Please install the setfont utility from the package
 \"kbd\" or reconfigure the font size." >&2
-                FONTFILES=''
-            fi
+                        FONTFILES=''
+                    fi
+                    ;;
+            esac
             ;;
-        *[a-zA-Z]16.fnt) VIDEOMODE=${VIDEOMODE:-80x25} ;;
-        *[a-zA-Z]14.fnt) VIDEOMODE=${VIDEOMODE:-80x30} ;;
-        *[a-zA-Z]8.fnt) VIDEOMODE=${VIDEOMODE:-80x43} ;;
+        freebsd)
+            FONTFILES=`findfile $fontdir $stdfont16`
+            [ "$FONTFILES" ] || FONTFILES=`findfile $fontdir $stdfontfallback16`
+            font=`findfile $fontdir $stdfont14`
+            [ "$font" ] || font=`findfile $fontdir $stdfontfallback14`
+            [ -z "$font" ] || FONTFILES="$FONTFILES $font"
+            font=`findfile $fontdir $stdfont8`
+            [ "$font" ] || font=`findfile $fontdir $stdfontfallback8`
+            [ -z "$font" ] || FONTFILES="$FONTFILES $font"
+            ;;
     esac
     if [ -n "$do_font" -a -z "$FONTFILES" ]; then
         echo Unable to find the required font.  No font will be configured. >&2
         do_font=''
     fi
-fi
-if [ "$kernel:::$VIDEOMODE" = freebsd::: ]; then
-    case "$FONTSIZE" in
-        16) VIDEOMODE=80x25 ;;
-        14) VIDEOMODE=80x30 ;;
-        8) VIDEOMODE=80x43 ;;
-        *)
-            echo "\
-Unable to determine the desired video mode. Please configure the value of
-VIDEOMODE or FONTSIZE." >&2
-            do_font=''
-            ;;
-    esac
-fi
-if [ "$do_font" = freebsd ]; then
-    report Using $VIDEOMODE as video mode.
 fi
 
 # FONTMAPFILE
@@ -610,11 +618,12 @@ fi
 
 case "$do_savekbd" in
     linux)
-	ckbcomp $acm_option $rules_option -model "$XKBMODEL" \
+	$installdir/bin/ckbcomp $acm_option $rules_option -model "$XKBMODEL" \
 	    "$XKBLAYOUT" "$XKBVARIANT" "$XKBOPTIONS" | gzip -9 >"$cached"
         ;;
     freebsd)
-	ckbcomp -freebsd $acm_option $rules_option -model "$XKBMODEL" \
+	$installdir/bin/ckbcomp -freebsd $acm_option $rules_option \
+	    -model "$XKBMODEL" \
 	    "$XKBLAYOUT" "$XKBVARIANT" "$XKBOPTIONS" >"$cached"
         ;;
 esac
@@ -644,9 +653,9 @@ fi
 case "$do_font" in
     linux*)
         if [ "$unicode" ]; then
-            run '' '' utf_start
+            run '' ECHO utf_start
         else
-            run '' '' utf_stop
+            run '' ECHO utf_stop
         fi
         ;;
 esac
@@ -655,8 +664,12 @@ esac
 if [ "$FONTFILES" ]; then
     case "$do_font" in
         freebsd)
-            run plain '' vidcontrol -f ${FONTFILES%% *}
-            run plain '' vidcontrol "$VIDEOMODE"
+            for font in $FONTFILES; do
+                run plain ECHO vidcontrol -f $font
+            done
+            if [ "$VIDEOMODE" ]; then
+                run in ECHO vidcontrol "$VIDEOMODE"
+            fi
             ;;
         linuxkbd)
             if [ "$FONTMAPFILE" ]; then
@@ -679,7 +692,7 @@ fi
 if [ "$CONSOLE_MAP" ]; then
     case "$do_font" in
         freebsd)
-            run plain '' vidcontrol -l "$CONSOLE_MAP"
+            run plain ECHO vidcontrol -l "$CONSOLE_MAP"
             ;;
         linuxkbd)
 	    run '-C ' -v setfont -m "$CONSOLE_MAP"
@@ -697,7 +710,7 @@ if [ "$do_font" ]; then
     [ -z "$SCREEN_HEIGHT" ] || STTY="$STTY rows $SCREEN_HEIGHT"
 
     if [ "$STTY" ]; then
-        run in '' stty $STTY
+        run in ECHO stty $STTY
     fi
 fi
 
@@ -727,9 +740,9 @@ fi
 if [ "$do_kbd" = linux ]; then
     if which kbd_mode >/dev/null; then
         if [ "$unicode" ]; then
-            run in '' kbd_mode -u
+            run in ECHO kbd_mode -u
         else
-            run in '' kbd_mode -a
+            run in ECHO kbd_mode -a
         fi
     else
         report kbd_mode is not accessible.  Unable to setup unicode/non-unicode keyboard mode.
@@ -746,21 +759,23 @@ fi
 if [ "$KMAP" ]; then
     case "$do_kbd" in
         linux) run plain '' loadkeys "$KMAP" ;;
-        freebsd) run plain '' kbdcontrol -l "$KMAP" ;;
+        freebsd) run plain ECHO kbdcontrol -l "$KMAP" ;;
     esac
 else
     case "$do_kbd" in
         linux)
-	    ckbcomp $acm_option $rules_option -model "$XKBMODEL" \
+	    $installdir/bin/ckbcomp $acm_option $rules_option \
+		-model "$XKBMODEL" \
 	        "$XKBLAYOUT" "$XKBVARIANT" "$XKBOPTIONS" \
                 | run plain '' loadkeys
             ;;
         freebsd)
-            TMPFILE=`mktemp` \
+            TMPFILE=`mktemp /tmp/console-setup.XXXXXX` \
                 || { echo Can not create temporary file >&2; exit 1; }
-	    ckbcomp -freebsd $acm_option $rules_option -model "$XKBMODEL" \
+	    $installdir/bin/ckbcomp -freebsd $acm_option $rules_option \
+		-model "$XKBMODEL" \
 	        "$XKBLAYOUT" "$XKBVARIANT" "$XKBOPTIONS" >$TMPFILE
-            run plain '' kbdcontrol -l $TMPFILE
+            run plain ECHO kbdcontrol -l $TMPFILE
             rm $TMPFILE
             ;;
     esac
