Create the link /usr/share/doc/console-setup in the postinst script

diff --git a/debian/console-setup.postinst b/debian/console-setup.postinst
--- a/debian/console-setup.postinst
+++ b/debian/console-setup.postinst
@@ -8,6 +8,20 @@ set -e
 CONFIGDIR=/etc/console-setup
 CONFIGFILE=/etc/default/console-setup
 
+# turn around bug in dpkg (#17624)
+cd /usr/share/doc
+if [ "$1" = configure ]; then
+    [ -d keyboard-configuration ] || exit 123 # should never fail
+    if [ -d console-setup -a ! -L console-setup ]; then
+        # in case the administrator has created some files
+        cp -a console-setup/* keyboard-configuration/ 2>/dev/null || true
+        rm -r console-setup
+        ln -s keyboard-configuration console-setup
+    elif [ ! -e console-setup ]; then
+        ln -s keyboard-configuration console-setup
+    fi
+fi
+
 if [ "$1" = "configure" ]; then
     
     db_get console-setup/codesetcode
